#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/config/bootstrap.php';


$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/config/console-main.php',
    require __DIR__ . '/config/console-main-local.php',
    require __DIR__ . '/config/test.php',
    require __DIR__ . '/config/test-local.php'
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
