<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 *
 *  php yii message/extract @app/modules/i18n/console/extractConfig.php
 *
 */
return [
    'color' => null,
    'interactive' => true,
    'help' => false,
    'silentExitOnException' => null,
    'sourcePath' => '@/app',
    'languages' => ['en-US'],
    'translator' => 'Yii::t',
    'sort' => false,
    'overwrite' => true,
    'removeUnused' => false,
    'markUnused' => true,
    'except' => [
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'db',
    'db' => 'db',
    'sourceMessageTable' => '{{%i18n_source_message}}',
    'messageTable' => '{{%i18n_message}}',
    'ignoreCategories' => []
];
